version: '3.1'

services:
  mongo:
    image: mongo:5
    container_name: mongo_pose
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mgpassd
    ports:
      - 27017:27017
    volumes:
      - /home/jharev/data/:/data/db
    networks:
    - exchange-net
  exchanged_pose:
    container_name: exchanged_pose
    image: exchanged:v1
    environment:
      APP_CONFIG_MONGODB_HOST: mongo_pose
      APP_CONFIG_MONGODB_DB: exchangedb
      APP_CONFIG_MONGODB_PORT: 27017
      APP_CONFIG_MONGODB_USER: mongouser
      APP_CONFIG_MONGODB_PSSWD: mgpassd
      APP_CONFIG_CORS_ALLOWED_ORIGIN_PATTERNS: "http://host.docker.internal:4200"
    ports:
      - 8010:8010
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - exchange-net
    depends_on:
      - mongo
networks:
  exchange-net:

      
